# These are supported funding model platforms

github: BuxOrg
custom: https://getbux.io/?utm_source=github&utm_medium=sponsor-link&utm_campaign=homebrew-bux-cli&utm_term=homebrew-bux-cli&utm_content=homebrew-bux-cli
