# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuxCli < Formula
  desc "CLI app for interacting with BUX
"
  homepage "https://github.com/BuxOrg/bux-cli"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BuxOrg/bux-cli/releases/download/v0.1.4/bux-cli_macOS_arm64.tar.gz"
      sha256 "5e500c10f070a468bdb69240b7769c624df449d637a400aaeb26d81b7e9013a0"

      def install
        bin.install "buxcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BuxOrg/bux-cli/releases/download/v0.1.4/bux-cli_macOS_64-bit.tar.gz"
      sha256 "ecc194187ca545865165470b070d7ee8c3a25c7bd358b52b14e440128cb135f2"

      def install
        bin.install "buxcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/BuxOrg/bux-cli/releases/download/v0.1.4/bux-cli_Linux_64-bit.tar.gz"
      sha256 "cbed8ea330590cd5498055c0c7438bc6ca33ebd362cadba0628092eacea2c56c"

      def install
        bin.install "buxcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BuxOrg/bux-cli/releases/download/v0.1.4/bux-cli_Linux_arm64.tar.gz"
      sha256 "5902813faf624e63d90743f9b6a9a50cebd5b2cae5001087eb20af5fb88b26db"

      def install
        bin.install "buxcli"
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repo for more information
    EOS
  end

  test do
    system "#{bin}/buxcli", "--version"
    system "#{bin}/buxcli", "-h"
  end
end
