# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuxCli < Formula
  desc "CLI app for interacting with BUX databases and servers
"
  homepage "https://github.com/BuxOrg/bux-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BuxOrg/bux-cli/releases/download/v0.1.0/bux-cli_macOS_arm64.tar.gz"
      sha256 "710b9b7c1f8eb58672ab3499b54c155aa6d53dac536c4208c589fc487d35e097"

      def install
        bin.install "buxcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BuxOrg/bux-cli/releases/download/v0.1.0/bux-cli_macOS_64-bit.tar.gz"
      sha256 "31c7a1d44e6b5460f290f0c3dc22578b0fc1a615840b2635ecb670214024f091"

      def install
        bin.install "buxcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/BuxOrg/bux-cli/releases/download/v0.1.0/bux-cli_Linux_64-bit.tar.gz"
      sha256 "d2bca1b80e0ea821b075861b2a1783e2c1287fef12bc96763af90e3569a7b62f"

      def install
        bin.install "buxcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BuxOrg/bux-cli/releases/download/v0.1.0/bux-cli_Linux_arm64.tar.gz"
      sha256 "4701d5448d2bd0b5fd1feb2b2c65b8f319308cb3be773cda5fbbd6c465ef7a35"

      def install
        bin.install "buxcli"
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repo for more information
    EOS
  end

  test do
    system "#{bin}/buxcli", "--version"
    system "#{bin}/buxcli", "-h"
  end
end
